---
title: "Homework Assignment 1"
author: "Student:  Anna Sehgal"
format: html
toc: false
---

## R scripts ran:
```{r}
#question 6
population_sample <- c(78, 84, 87, 70, 92, 78, 59, 82, 81, 64, 97, 76)

population_sample
# 6a 
mean(population_sample)
population_mean <-round(mean(population_sample), 1)
population_mean

#6b
random_sample <- c(92, 82, 87)
random_sample
mean(random_sample)
random_sample_mean <- mean(random_sample)

if(random_sample_mean > population_mean) {
    print("random mean sample is greater than population mean sample.")
} else if (random_sample_mean == population_mean){
    print("random mean sample is equal to population sample mean.")
} else {
    print("populatioin sample mean is greater than random sample mean.")
}

#6c
population_sample
population_mean_data <-mean(population_sample)
population_mean_data

sample2 <- c(59, 84, 64)
sample2
mean(sample2)
random_sample_2 <- mean(sample2)

if(random_sample_2 > population_mean_data) {
    print("random mean sample is greater than population mean sample.")
} else if (random_sample_2 == population_mean_data){
    print("random mean sample is equal to population sample mean.")
} else {
    print("population sample mean is greater than random sample mean.")
}

#Question 7
sample_question7 <- c(3, 17, 25, 15, 11, 17, 28, 15, 4)
sample_question7
# reference (for standard deviation in R studio): https://www.datacamp.com/tutorial/r-sd
sd(sample_question7)
standard_div <- sd(sample_question7)
standard_div
round(standard_div, 2)

# Question 8
sleep_data_sample <- c(6.5, 6.5, 7, 7, 5.5, 7.5, 6, 8.5, 8, 5.5, 5.5, 5, 6.5, 8, 5)
sleep_data_sample

#8a
# The range is the difference between the largest and smallest values in a sample
max_sample <- max(sleep_data_sample)
min_sample <- min(sleep_data_sample)
max_sample
min_sample

range_sample_sleep <- (max_sample - min_sample)
range_sample_sleep

#8b
sleep_data_sample
standard_div_sleep <- sd(sleep_data_sample)
standard_div_sleep
standard_div_sleep_rounded <- round(standard_div_sleep, 2)
standard_div_sleep_rounded

#8c
sleep_data_sample
IQR(sleep_data_sample)

#8d
new_55_sleep_data_sample <- sleep_data_sample
#fix position 5 arr in data to 55
new_55_sleep_data_sample[5] <- 55

new_55_sleep_data_sample

new_max_sample <- max(new_55_sleep_data_sample)
new_min_sample <- min(new_55_sleep_data_sample)
new_max_sample
new_min_sample

new_range_sample_sleep <- (new_max_sample - new_min_sample)
new_range_sample_sleep

new_55_sleep_data_sample
new_standard_div_sleep <- sd(new_55_sleep_data_sample)
new_standard_div_sleep
new_standard_div_sleep_rounded <- round(new_standard_div_sleep, 2)
new_standard_div_sleep_rounded

new_55_sleep_data_sample
IQR(new_55_sleep_data_sample)

# Question 9
grades_sample <- c(98, 92, 91, 91, 87, 85, 85, 82, 77, 76, 61)

grades_sample

grades_mean <- mean(grades_sample)
grades_median <- median(grades_sample)
grades_mean
grades_median

# histogram for 9
hist(grades_sample)

```

---

# Instructions

Please type your answer within the document and render a html file to submit to Canvas

---

## 1 — Identify each variable as quantitative or qualitative
**Definitions:**

- Quantative data = related to numbers or is measureable is empirical data.
- While Qualitative data = related to descriptive or based on interpretation like emotion, langauge, or category.


A. The height of a newborn in a hospital is `__Quantative_data__`

B. The age of a football player is `__Quantative_data__`

C. The student social security number is `__Qualitative_data__` 
#Though ssn has numbers linked to a student, it is to identify rather than to measure something.

D. The blood type of a middle school teacher is `__Qualitative_data__`

---

## 2 — Classify each quantitative variable as discrete or continuous
As learned in class:

* discrete variable are whole number which can do a certain job; values can be enuramated (numerical values with jumps).

* while continious is basically dependening on measurement, accuracy; can be any number on number-line (possible values can take a continuum of number).

* another thing I found was that discrete data is counter and has spaced between values while continuous has constant sequence within a defined range.

A. Number of siblings of a student is `__Discrete_variable__`

B. Number of dead batteries in a box of dozen batteries is `__Discrete_variable__`

C. Time it takes to respond to a question is `__Continuous_variable__`

D. Systolic blood pressure is `__Continuous_variable__`

---

## 3 — Observational study or designed experiment?

A. A study of stress and its relationship to obesity where participants were surveyed: `__Observational_study__`

B. Longitudinal study of healthy people to see who develops lung cancer (smoking status recorded): `__Observational_study__`

C. Clinical trial randomly dividing participants into two diet groups to measure blood pressure: `__Designed_experiment__`

D. Rats randomly divided into exposed/unexposed groups to radiation and observed for cancer: `__Designed_experiment__`

---


## 4 — Population / variable / statistic questions

A Lake Tahoe Community College instructor is interested in the mean number of days math students are absent during a quarter.

a. What is the population she is interested in?  `__(D)_All Lake Tahoe Community College math students__`

* (A) All Lake Tahoe Community College students
* (B) All Lake Tahoe Community College English students
* (C) All Lake Tahoe Community College students in her classes
* **(D) All Lake Tahoe Community College math students**


b. Consider X represent the number of days a LTCC math student is absent. In this case X is an example of a: `_(A)_Variable___`

#it should be a variable because it depends on student to student.

* **(A) Variable** 
* (B) Population
* (C) Statistic
* (D) Data

c. The instructor’s sample produces a mean number of days absent of `3.5` days. This value is an example of a: `__(C)_Statistic__`

* (A) Parameter
* (B) Data
* **(C) Statistic**
* (D) Variable


---

## 5 — Representative or non-representative?

For each study below mark A (REPRESENTATIVE) or B (NON-REPRESENTATIVE):

1. Sample of 300 dentists from Seattle used to estimate median income of all Seattle residents. `___Non-representative___`

2. Sample of 200 professional football players to estimate mean weight of all adult males.  `___Non-representative___`

3. Simple random sample of 10 men over age 18 to estimate mean height of all adult males.  `___Representative___`

4. Simple random sample of 1000 voters to determine candidate chances.  `___Representative___`

5. Sample of 400 patients from a local hospital to estimate mean cholesterol of U.S. citizens.  `___Non-Representative___`

---



## 6 — Population & sample means (12 students)

Population test scores: `78, 84, 87, 70, 92, 78, 59, 82, 81, 64, 97, 76`

A. What is the population mean grade? (round to 1 decimal)
Answer: `___79.0____`

B. A random sample of size 3: sample `92, 82, 87` — sample mean = `___87___`; compare to population mean: `___random sample mean is greater than population sample mean___`.

C. Another sample of size 3: sample `59, 84, 64` — sample mean = `___69___`; compare to population mean: `___population mean is greater than population sample mean___`.

D. What can you conclude about relationship between a sample mean and the population mean? (`__(A)_The sample mean varies from sample to sample.__`)

* ***(A) The sample mean varies from sample to sample.***
* (B) No matter how many times we select a sample, the sample mean is always equal to the population mean.
* (C) Every time we select a sample, the sample mean always overestimates the population mean.
* (D) Every time we select a sample, the sample mean always underestimates the population mean.



---

## 7 — Sample standard deviation

Given sample: `3, 17, 25, 15, 11, 17, 28, 15, 4`

A. What symbol denotes the sample standard deviation? `___s___`

B. Find the sample standard deviation (round to 2 decimals): `___8.35___`

---

## 8 — Sleep survey (15 students)

Sample data: `6.5, 6.5, 7, 7, 5.5, 7.5, 6, 8.5, 8, 5.5, 5.5, 5, 6.5, 8, 5`

A. Range = `___3.5___`

B. Standard deviation = `___1.13___` (round to 2 decimals)

C. IQR = `__1.75__`

D. Suppose the 5th data value was recorded as `55` instead of `5.5`. Recompute new range and SD:

* New range = `___50___`
* New SD = `___12.54___` (round to 2 decimals)
* New IQR = `___2___`




## 9 — Compute mean & median; skewness

Grades: `98, 92, 91, 91, 87, 85, 85, 82, 77, 76, 61`

Mean = `___84.09091___`

Median = `___85___`



- Present the Histogram
```{R}
hist(grades_sample)
```


- Is this dataset `SKEWED RIGHT`, `SYMMETRIC`, or `SKEWED LEFT`?

  ***The dataset is SKEWED LEFT in the histogram.***

